### ISSUE TITLE
Enable/Disable Plugin

### ISSUE THREAD

**Issue by frami** [mibexsoftware/sonar-bitbucket-plugin#1]
Is it possible to enable/disable the plugin? I don't want to use it for every sonar run and not for every project.

**Comment by mrueegg** [comment]
Currently, the plug-in is considered active if the parameter "sonar.bitbucket.accountName" is set. If not, it won't run. Are you suggesting a parameter like "sonar.bitbucket.enabled" here so that you don't need to remove the other parameters and can easily enable/disable the plug-in?

**Comment by frami** [comment]
If it only active with the parameter "sonar.bitbucket.accountName", then it's ok for me.

I have the following problem. I execute the sonarqube analyze with the sonarqube plugin (http://docs.sonarqube.org/display/SONAR/Analyzing+with+Gradle) under gradle 2.8. I have nothing configured for the bitbucket plugin, but I get this exception after a successful sonarqube analysis.

    Caused by: java.lang.IllegalStateException: Either team-based API or an OAuth user authentication   has to be used
        at ch.mibex.bitbucket.sonar.client.ClientAuthentication.configure(AuthenticationFilter.scala:70)
        at ch.mibex.bitbucket.sonar.client.BitbucketClient.createJerseyClient(BitbucketClient.scala:34)
        at ch.mibex.bitbucket.sonar.client.BitbucketClient.<init>(BitbucketClient.scala:26)
        at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)

**Comment by mrueegg** [comment]
I fixed that bug a week ago, but haven't released it yet. Could you please upgrade to the new version 1.0.1?

**Comment by frami** [comment]
Thank you, it work's with the version 1.0.1. Now I can start testing it. :-)
