### ISSUE TITLE
Plugins fails with "No access token found" message

### ISSUE THREAD

**Issue by emersoncod** [mibexsoftware/sonar-bitbucket-plugin#2]
Hi,

sorry if this is trivial, this is my first try with the plugin (also oauth).

I create a bitbucket repository and wanted to run the plugin on it.

My command is 
```
mvn clean verify sonar:sonar --batch-mode --errors -Dsonar.bitbucket.repoSlug=sonar-pull-request-plugin-test -Dsonar.bitbucket.accountName=username -Dsonar.bitbucket.oauthClientKey=key -Dsonar.bitbucket.oauthClientSecret=secret -Dsonar.bitbucket.branchName=master -Dsonar.analysis=issues
```
this fails with 
>Caused by: java.lang.IllegalStateException: No access token found
	at ch.mibex.bitbucket.sonar.client.ClientAuthentication.ch$mibex$bitbucket$sonar$client$ClientAuthentication$$createOauthAccessToken(AuthenticationFilter.scala:94)
	at ch.mibex.bitbucket.sonar.client.ClientAuthentication$$anon$1.<init>(AuthenticationFilter.scala:65)
	at ch.mibex.bitbucket.sonar.client.ClientAuthentication.configure(AuthenticationFilter.scala:64)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.createJerseyClient(BitbucketClient.scala:34)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.<init>(BitbucketClient.scala:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	[....]
	... 23 more

what I did

1. on bitbucket i went "Manage Account" -> "OAuth" -> "Add consumer"
2. gave it an arbitrary name, some description and no callback URL nor URL (didn't know what to enter there). 
3. Permissions set to "Repositories" "Write" and "Pull requests" "Write"
4. entered the given key as sonar.bitbucket.oauthClientKey and the secret as onar.bitbucket.oauthClientSecret

I'm not sure what you mean with 
>the client key of the OAuth consumer created for **this application** here

how can I create one for this application ? I can only create an arbitrary it seems.

Thanks for help - and sorry if this is not actually an issue of the project, i dont know another way to request this.

**Comment by mrueegg** [comment]
Hi,

You have to specify a callback URL. You can set this to anything you want, it really doesn't matter as long as you have defined one. I'll update the documentation accordingly. 

Hope this helps.

**Comment by emersoncod** [comment]
this helped. thanks for the hint
