### ISSUE TITLE
Plugin fails to run in Jenkins

### ISSUE THREAD

**Issue by mmaihoefner** [mibexsoftware/sonar-bitbucket-plugin#26]
Hello,

we have the problem that the plugin stopped working today out of nowhere in our Jenkins build. The stacktrace is as follows:
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:62)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:57)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:57)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:56)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:212)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestsPage$1(BitbucketClient.scala:55)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findPullRequestsWithSourceBranch$1.apply(BitbucketClient.scala:72)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findPullRequestsWithSourceBranch$1.apply(BitbucketClient.scala:71)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:219)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findPullRequestsWithSourceBranch(BitbucketClient.scala:71)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.findPullRequestsForConfiguredBranch(SonarReviewPostJob.scala:36)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:133)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:82)
	at org.sonarsource.scanner.cli.Main.main(Main.java:66)

I saw that you recommended to Query the Bitbucket REST API which gave us the following result:
...,
"destination": {
    "commit": {
      "hash": "aeee8fe7f208",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/repositories/{owner}/{repo_slug}/commit/aeee8fe7f208"
        }
      }
    },
    ...
  },
...

Is this issue related to https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/23 or is there a different problem? Any help would be much appreciated.

**Comment by MichaelRueegg** [comment]
Hi,

Yes, this is indeed related to #23. In my code, I always expect `destination->commt->hash` to be available. This is the case in your example JSON, but is it also the case for all your open pull requests in this repository? This is currently required by the implementation. I think I will change this for the next release to only require this for pull requests with a source branch equal to the branch being analyzed, but I would be interested to see an example of a pull request which doesn't have the destination commit hash set. I would like to understand when this can happen. Could you please have a look at your open pull requests?

**Comment by mmaihoefner** [comment]
Hi Micheal,

the Problem was solved after we merged the Pull Request with the JSON I sent you yesterday, I am not sure why though. Here is more of the JSON for that Pull Request:
{
  "merge_commit": null,
  "description": "Added create script for Database.",
  "links": {
    ...
  },
  "title": "Bug-ISHL-8",
  "close_source_branch": true,
  "reviewers": [
    ...
  ],
  "destination": {
    "commit": {
      "hash": "aeee8fe7f208",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/repositories/{owner}/{repo_slug}/commit/aeee8fe7f208"
        }
      }
    },
    "repository": {
    ...
    },
    "branch": {
      "name": "Development"
    }
  },
  "state": "OPEN",
  "closed_by": null,
  "source": {
    "commit": {
      "hash": "36b5419cfcab",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/repositories/{owner}/{repo_slug}/commit/36b5419cfcab"
        }
      }
    },
    "repository": {
      ...
    },
    "branch": {
      "name": "Bug-ISHL-8"
    }
  },
  "comment_count": 1,
  "author": {
    ...
    }
  },
  "created_on": "2016-05-13T09:08:56.605289+00:00",
  "participants": [
    ...
  ],
  "reason": "",
  "updated_on": "2016-05-19T12:01:21.844354+00:00",
  "type": "pullrequest",
  "id": 346,
  "task_count": 0
}

sadly i am not allowed to share the entire JSON with you, but I hope this can help you.

**Comment by MichaelRueegg** [comment]
Thanks for the JSON, but in that one the destination commit is set. Would you mind to send me the JSON of the pull request if this error ever occurs again? I'll therefore leave this issue open for the moment. I would really like to know under what circumstances a pull request doesn't have a destination commit.

**Comment by mmaihoefner** [comment]
The JSON I send you is the JSON of the "broken" Pull Request, I don't know why it has the commit hash set. We checked all the Pull Request responses and all of them had the commit hash set. I am really sorry that I can't help you with this issue, because i also would like to understand why this is happening we had over 300 Pull Requests before which all worked fine its just this one for some reason that didn't work.
