### ISSUE TITLE
Not able to override the  sonar.bitbucket.minSeverity 

### ISSUE THREAD

**Issue by lcasat** [mibexsoftware/sonar-bitbucket-plugin#27]
I tried to override the minimum severity by adding command line parameter to my maven job, but that failed. 
-Dsonar.bitbucket.minSeverity= CRITICAL

maven-plugin:3.0.2:sonar (default-cli) on project ia-marketing: requirement failed: [sonar4bitbucket] Invalid severity 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)

**Comment by MichaelRueegg** [comment]
Hi, could you please remove the space in front of " CRITICAL" and try again?

**Comment by lcasat** [comment]
That space is the issue. Now it's working. Thanks.
