### ISSUE TITLE
Sonar Crashes After Installing

### ISSUE THREAD

**Issue by expandlab** [mibexsoftware/sonar-bitbucket-plugin#31]
When installing plugin, Sonar will start, but then very quickly shuts itself down.

Here's the log output where it's failing:

```
2016.11.06 11:46:48 INFO  ce[][o.s.p.ProcessEntryPoint] Starting ce
2016.11.06 11:46:48 INFO  ce[][o.s.ce.app.CeServer] Compute Engine starting up...
2016.11.06 11:46:49 INFO  ce[][o.e.plugins] [Tom Thumb] modules [], plugins [], sites []
2016.11.06 11:46:50 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2016.11.06 11:46:50 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:mysql://localhost:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
2016.11.06 11:46:52 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /etc/sonarqube
2016.11.06 11:46:52 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2016.11.06 11:46:53 ERROR ce[][o.s.ce.app.CeServer] Compute Engine startup failed
java.lang.IllegalStateException: Can not extract sonar-plugin-api-deps.jar to /etc/sonarqube/temp/tmp/sonar-plugin-api-deps3150398346094117636jar
	at org.sonar.core.platform.PluginClassloaderFactory.extractCompatibilityModeJar(PluginClassloaderFactory.java:134) ~[sonar-core-6.1.jar:na]
	at org.sonar.core.platform.PluginClassloaderFactory.create(PluginClassloaderFactory.java:86) ~[sonar-core-6.1.jar:na]
	at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:72) ~[sonar-core-6.1.jar:na]
	at org.sonar.ce.container.CePluginRepository.start(CePluginRepository.java:71) ~[sonar-ce-6.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_60]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-6.1.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:n2016.11.06 11:46:54 WARN  web[][o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(Unknown Source)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
2016.11.06 11:46:54 INFO  web[][o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.11.06 11:46:55 WARN   es[][o.e.c.r.a.decider]  [sonarqube] high disk watermark [90%] exceeded on [hjAqbvqFR9qgM4Yl-V5PIw][sonarqube][/etc/sonarqube/data/es/sonarqube/nodes/0] free: 29.7mb[1.5%], shards will be relocated away from this node
2016.11.06 11:46:55 INFO   es[][o.e.c.r.a.decider]  [sonarqube] rerouting shards: [high disk watermark exceeded on one or more nodes]
2016.11.06 11:46:55 INFO  web[][o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.11.06 11:46:55 INFO  web[][o.s.s.a.TomcatAccessLog] Web server is stopped
2016.11.06 11:46:56 INFO  app[][o.s.p.m.Monitor] Process[web] is stopped
2016.11.06 11:46:56 INFO  app[][o.s.p.m.Monitor] Process[es] is stopping
2016.11.06 11:46:56 INFO   es[][o.s.p.StopWatcher]  Stopping process
2016.11.06 11:46:56 INFO   es[][o.elasticsearch.node]  [sonarqube] stopping ...
2016.11.06 11:46:56 INFO   es[][o.elasticsearch.node]  [sonarqube] stopped
2016.11.06 11:46:56 INFO   es[][o.elasticsearch.node]  [sonarqube] closing ...
2016.11.06 11:46:56 INFO   es[][o.elasticsearch.node]  [sonarqube] closed
2016.11.06 11:46:57 INFO  app[][o.s.p.m.Monitor] Process[es] is stopped
<-- Wrapper Stopped

```

Only way to resolve was to remove sonar-bitbucket-plugin-1.1.5.jar from the plugin extensions.

**Comment by mrueegg** [comment]
Hi,

I also have the plug-in installed on a SonarQube 6.1 instance but haven't experienced any issues. On which platform does this happen? Is the directory `/etc/sonarqube/temp/tmp/` writable for the process running SonarQube?
