### ISSUE TITLE
The plug-in should not yield an 404 exception when there are no open pull requests for the given branch

### ISSUE THREAD

**Issue by mrueegg** [mibexsoftware/sonar-bitbucket-plugin#4]
Currently, the plug-in yields the following exception in that case:

Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET returned a response status of 404 Not Found
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:204)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestsPage$1(BitbucketClient.scala:51)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findPullRequestsWithSourceBranch$1.apply(BitbucketClient.scala:68)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findPullRequestsWithSourceBranch$1.apply(BitbucketClient.scala:67)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:214)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findPullRequestsWithSourceBranch(BitbucketClient.scala:67)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.findPullRequestsForConfiguredBranch(SonarReviewPostJob.scala:36)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
	at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 24 more

**Comment by mrueegg** [comment]
Could not reproduce. Reason was that the wrong account name was chosen.
