### ISSUE TITLE
Pull Requests not Analyzed

### ISSUE THREAD

**Issue by alfredantony012** [mibexsoftware/sonar-bitbucket-plugin#44]
I have 2 questions here.

1. We are using teamcity as the CI tool and Bitbucket as source control. I tried to analyze a pull request which is having around 250+ files and it failed. I think the issue is due to time take for loading the differences. Is there a way to increase the timeout? Error message is below 

{"type": "error", "error": {"message": "Unable to respond in time"}}
[14:43:56][Step 7/7] 
[14:43:56][Step 7/7] INFO: ------------------------------------------------------------------------
[14:43:56][Step 7/7] INFO: EXECUTION FAILURE
[14:43:56][Step 7/7] INFO: ------------------------------------------------------------------------
[14:43:56][Step 7/7] Total time: 29.980s
[14:43:56][Step 7/7] Final Memory: 12M/190M
[14:43:56][Step 7/7] ERROR: Error during Sonar runner execution
[14:43:56][Step 7/7] ERROR: Unable to execute Sonar
[14:43:56][Step 7/7] INFO: ------------------------------------------------------------------------
[14:43:56][Step 7/7] ERROR: Caused by: GET https://bitbucket.org/!api/2.0/repositories/*****/******/diff/******/*********:3b7f6db28f68%0D107c29eab8b3?context=0 returned a response status of 555 null

2. We have develop branch and release branches and around 15+ development teams available. Every branch name is unique and pull request will be raised for release branch. Is there a way to analyze the all the pull requests raised for release branch? Using below parameters. Currently i am giving source branch name for every analysis

-Dsonar.bitbucket.repoSlug=***********
-Dsonar.bitbucket.accountName=*********
-Dsonar.bitbucket.teamName=***********
-Dsonar.bitbucket.oauthClientKey=*****************
-Dsonar.bitbucket.oauthClientSecret=***************
-Dsonar.bitbucket.branchName=$GIT_BRANCH
-Dsonar.host.url=************
-Dsonar.login=************
-Dsonar.password=************
-Dsonar.analysis.mode=issues
-Dsonar.bitbucket.minSeverity=INFO
-Dsonar.verbose=true
-Dsonar.bitbucket.approvalFeatureEnabled=false

**Comment by mrueegg** [comment]
Hi,

1. This is a known issue (e.g. see
https://community.atlassian.com/t5/Answers-Developer-Questions/API-2-0-GET-diff-of-specific-file-in-a-pull-request/qaq-p/553690). The REST service to get the pull request diff times out for large pull requests. I'll discuss this with Atlassian to see if this can be addressed.

2. No, we do not have special support for analyzing all pull requests of a release branch currently. With release 1.2.0 we support analyzing pull requests by using a new parameter

          -Dsonar.bitbucket.pullRequestId=123

Does that help you? If not, could you please create a new feature request for this?

**Comment by mrueegg** [comment]
@alfredantony012 Hi. To be able to address this with the Bitbucket team, I need an example. Would you be able to share the pull request that causes time outs or is it private?

**Comment by alfredantony012** [comment]
Hi,
Sorry. We can't share the pull request details.It's a private repository.

**Comment by LadyWarden147** [comment]
Hi!

I am facing issue with not reporting issues on my PR.

What I see is "SonarQube Analysis reported no issues. Take a chocolate :-)" even if I commited deliberately bad code.

_Could you please advise the correct behavior of commenting:_
_So the situation is like this:_

- I have a branch, when my developing stuff is finished (e.g. I modified files A, B, C) - I create the PR.
- On this step, when PR is created - **should comments  be visible only for new files** (for A, B, C)?
- Then I commit some code (in file D) in existing branch  (PR stays the same) - **should comments  be visible only for new files of new commit + previous files** (for A, B, C and D)?

Many thanks,
Anna

**Comment by danieljimenez** [comment]
I'm seeing the same thing as Anna above.

**Comment by mrueegg** [comment]
Please excuse my late reply. Comments should be created for all issues on changed lines, so for existing files with changes as well (A, B, C + D). Of course, the plug-in can only create comments when it is run when the pull request already exists. 

To be able to analyze why the plug-in doesn't work correctly in your case, I need the debug logs for a build run. Could you please follow the steps described in the Troubleshooting section (https://github.com/mibexsoftware/sonar-bitbucket-plugin#troubleshooting) and attach the debug logs? That would help me much!

**Comment by Bheesma** [comment]
I have created a pull request. The plugin analyses and provides comment at appropriate places. Now I do not see the comments, but I push a piece of code again. When the plugin runs again, it deletes all existing comments and puts the comments on newly changed lines only. This prevents me from fixing the old comments. I am using MSBuild runner and Preview analysis mode. Is there any setting to make the plugin stop deleting existing comments?

**Comment by mjblue** [comment]
I see this issue too and as pointed out error 555 is returned when a diff is too l arge ( I am seeing this on a cleanup PR which deletes over 1000 files from the repo ). I appreciate we can skip the diff on this so am happy that if we get a 55 then it just reports a message saying something like 'sorry couldn't analyse this PR it's just too darn big". The problem is that it throws an exception and the build fails as the error isn't caught

`INFO: [sonar4bitbucket] Plug-in is active and will analyze pull request #2267...
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 28.091s
INFO: Final Memory: 49M/371M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
com.sun.jersey.api.client.UniformInterfaceException: GET https://api.bitbucket.org/2.0/repositories/pangaea-ondemand/pangaea2/diff/pangaea-ondemand/pangaea2:a145351f7b13%0D016bd4e6a24a?from=pullrequest&context=0 returned a response status of 555 null
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
	at com.sun.jersey.api.client.WebResource.get(WebResource.java:191)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.getPullRequestDiff(BitbucketClient.scala:197)
	at ch.mibex.bitbucket.sonar.diff.IssuesOnChangedLinesFilter.filter(IssuesOnChangedLinesFilter.scala:15)`


Can we at least catch the exception and report as such?

**Comment by O5ten** [comment]
I also have this exact same issue as the original poster. Any idea on what the problem is? :)

**Comment by thuypt** [comment]
I have the same issues when PRs contains library upgrade (jar file). How could I ignore these diff out of analyse, they could come from a particular directory?
