### ISSUE TITLE
NullPointerException when fetching pull request with deleted comments

### ISSUE THREAD

**Issue by mikkopiu** [mibexsoftware/sonar-bitbucket-plugin#67]
### Expected Behavior

SonarQube Scanner in Jenkins (using this plugin) should update Bitbucket pull request comments with new scan statuses. 

### Actual Behavior

Received `NullPointerException` with stack trace:

```scala
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:145)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:149)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:312)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:148)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:172)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:319)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:41)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:25)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:25)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:66)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:84)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

### Plug-in version, SonarQube version, CI system, build type

* Plugin version: 1.2.1
* SonarQube version: 6.5 (build 27846)
* CI system: Jenkins, version: 2.89.1
* Build type: Jenkins Pipeline, JavaScript build

The NPE is coming from this line: https://github.com/mibexsoftware/sonar-bitbucket-plugin/blob/v1.2.1/src/main/scala/ch/mibex/bitbucket/sonar/client/BitbucketClient.scala#L145

and when I tested the Bitbucket API endpoint it (`fetchPage`) is using (`https://api.bitbucket.org/2.0/repositories/{account}/{repoSlug}/pullrequests/{prId}/comments`), I noticed that deleted comments are returned with a `user` value of `null`, e.g.:

```json
{
    "pagelen": 10,
    "size": 51,
    "values": [
        {
            "links": <snip>,
            "deleted": true,
            "pullrequest": <snip>,
            "content": {
                "raw": "",
                "markup": "markdown",
                "html": ""
            },
            "created_on": "2017-11-24T11:38:30.264053+00:00",
            "user": null,
            "inline": {
                "to": 376,
                "from": null,
                "path": "fake.js"
            },
            "updated_on": "2017-11-29T14:56:42.214876+00:00",
            "type": "pullrequest_comment",
            "id": 50383913
        },
    ]
}
```

I assume this bit then fails because `user` is `null`, and therefore cannot have a property `uuid`:

```scala
comment("user").asInstanceOf[Map[String, Any]]("uuid").asInstanceOf[String] equals uuid
```

It sounds like something has changed in the Bitbucket REST API but I wasn't able to find any changelogs etc. describing such a change. This has been working fine so far, started happening today.

**Comment by mikkopiu** [comment]
I'm not too familiar with Scala, would this be an idiomatic fix:

```scala
def isFromUs(comment: Map[String, Any]): Boolean = {
  val user = comment("user").asInstanceOf[Map[String, Any]]
  if (user == null) false else user("uuid").asInstanceOf[String] equals uuid
}
```

or possibly:

```scala
    def isFromUs(comment: Map[String, Any]): Boolean =
      Option(comment("user").asInstanceOf[Map[String, Any]])
        .getOrElse(Map("uuid" -> null))("uuid").asInstanceOf[String] equals uuid
```

?

**Comment by rhaex** [comment]
We are having the exact same issue.

Plugin version: 1.2.1
SonarQube version: 6.7 (build 33306)
CI system: Bamboo, version: 6.2.1 (build 60208)
Build type: Maven3 using 'Sonar for Bamboo plugin', Java build

**Comment by nfalco79** [comment]
same issue here

**Comment by Jtag84** [comment]
Same issue

Plugin version: 1.2.1
SonarQube version: 6.2
Bamboo version: 5.14.4.1 build 51417

**Comment by andrew-makarenko** [comment]
I experience the same issue

**Comment by mikkopiu** [comment]
@kmalmur : I think 1.2.2 is the previously released version, and the fix in #68 hasn't made it into a release yet.

**Comment by kmalmur** [comment]
@mikkopiu from what I see in the change log, the fix should be already there:
https://github.com/mibexsoftware/sonar-bitbucket-plugin/compare/v1.2.2...master

**Comment by mikkopiu** [comment]
Oh, so did you build your own version from `master`?

**Comment by kmalmur** [comment]
@mikkopiu sorry, I've used a wrong diff. You are right, this is not released yet. Do you have any estimations of the next release?

**Comment by mikkopiu** [comment]
@kmalmur : Unfortunately not, I'm just a contributor -- maybe @mrueegg might know?

**Comment by rhaex** [comment]
You could clone (or download the zip of) the master branch, and on the root run a ```mvn package```, and upload the generated jar to your Sonar server in the meantime. That's how I did it until it is actually shipped in a new release.

**Comment by mrueegg** [comment]
I'll try to release a new version today.

**Comment by mrueegg** [comment]
@kmalmur I've just created a new release 1.2.3. Please build a JAR from this release with `mvn clean package`.

**Comment by jonbakerarco** [comment]
Will there be a release JAR for this like there was for 1.2.1 and before or do we need to build it ourselves?

**Comment by NielsClay** [comment]
When will this be released?
Is there a .jar available?
