### ISSUE TITLE
Some pull requests fail to add comments in bitbucket

### ISSUE THREAD

**Issue by sreeramk08** [mibexsoftware/sonar-bitbucket-plugin#73]
### Expected Behavior
Normal behavior...has been working fine for several months now.  Other than the bitbucket outage, nothing has changed.  

When a pull request is created or updated, a jenkins job is run thanks to the pull request builder.  This plugin then adds the comments in the PR.  

### Actual Behavior

Not all pull requests fail.  Some do and then as though it was fixed, everything is fine.  When they fail, this message is posted in Jenkins console output.  As is shown below, the sonarqube analysis actually worked fine.  

INFO: ANALYSIS SUCCESSFUL
INFO: [sonar4bitbucket] Version check not possible because server.getVersion returned null
INFO: Executing post-job ch.mibex.bitbucket.sonar.review.SonarReviewPostJob
INFO: [sonar4bitbucket] Plug-in is active and will analyze project xcipio
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 11.723s
INFO: Final Memory: 59M/352M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:104)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4$$anonfun$apply$2.apply(BitbucketClient.scala:109)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4$$anonfun$apply$2.apply(BitbucketClient.scala:109)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4.apply(BitbucketClient.scala:109)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4.apply(BitbucketClient.scala:108)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:244)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:107)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:131)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:130)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:251)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:130)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:20)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$executeOn$1.apply(SonarReviewPostJob.scala:18)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.executeOn(SonarReviewPostJob.scala:18)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:63)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:53)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:82)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
Build step 'Execute shell' marked build as failure

### Plug-in version, SonarQube version, CI system, build type

Sonarqube server: 6.1
Plugin version: 1.1.7
Jenkins: 2.91
Bitbucket pull request plugin: 1.4.26

Thanks for your help
Sam

**Comment by sreeramk08** [comment]
Hello.  Anything I should try to fix this?  Is anyone encountering this issue?

**Comment by nwoolls** [comment]
@sreeramk08 have you seen https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/67? Does building from `master` using 1.2.3 fix the issue?

**Comment by sreeramk08** [comment]
Hi

  Sorry for the late reply.  after installing the latest 1.2.3 released version, my problems went away.  😊 thanks

Sam

________________________________

**Comment by mrueegg** [comment]
Thanks for your feedback, this is good news! And please excuse my late reply...
