### ISSUE TITLE
NullPointerException BitbucketClient.scala:145

### ISSUE THREAD

**Issue by gtcon-david-cerqueira** [mibexsoftware/sonar-bitbucket-plugin#78]
### Expected Behavior

Sonar should analyse the code and create comments on the Pull Request.

### Actual Behavior

Plugin fails with NullPointerException.

In the last few weeks we are seeing  this error frequently. Sometimes when we decline the Pull Request and create another one with the same information it works, but other times don't.

`[INFO] 16:28:58.927 ANALYSIS SUCCESSFUL
Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 1 * Client out-bound request
1 > POST https://bitbucket.org/site/oauth2/access_token
1 > Content-Type: application/x-www-form-urlencoded
1 > Authorization: Basic MYCREDENTIAL
grant_type=client_credentials

Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 1 * Client in-bound response
1 < 200
1 < Server: nginx
1 < X-Content-Type-Options: nosniff
1 < Connection: keep-alive
1 < X-Static-Version: 8f1aaf1af99e
1 < X-Version: 8f1aaf1af99e
1 < Last-Modified: Wed, 07 Mar 2018 16:28:59 GMT
1 < Date: Wed, 07 Mar 2018 16:28:59 GMT
1 < X-Frame-Options: SAMEORIGIN
1 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
1 < X-Render-Time: 0.029228925705
1 < Cache-Control: no-cache, no-store, must-revalidate, max-age=0
1 < ETag: "eb70bb8019dac537facb2af495c0c18e"
1 < X-Served-By: app-172
1 < Vary: Accept-Language, Cookie
1 < Expires: Wed, 07 Mar 2018 16:28:59 GMT
1 < Content-Length: 226
1 < Content-Language: en
1 < X-Request-Count: 229
1 < Content-Type: application/json
1 < 
{"access_token": "MYTOKEN", "scopes": "pullrequest:write account", "expires_in": 3600, "refresh_token": "MYTOKEN", "token_type": "bearer"}

[DEBUG] 16:28:59.273 Post-jobs : Sonar Plug-in for Bitbucket Cloud (wrapped)
[INFO] 16:28:59.273 Executing post-job Sonar Plug-in for Bitbucket Cloud (wrapped)
Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 2 * Client out-bound request
2 > GET https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests?page=1&pagelen=50&state=OPEN
2 > Accept: application/json
2 > Content-Type: application/json
2 > Authorization: Bearer MYTOKEN

Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 2 * Client in-bound response
2 < 200
2 < X-Accepted-OAuth-Scopes: pullrequest
2 < X-Credential-Type: oauth2
2 < Server: nginx
2 < X-Content-Type-Options: nosniff
2 < Connection: keep-alive
2 < X-Static-Version: 8f1aaf1af99e
2 < X-Version: 8f1aaf1af99e
2 < Date: Wed, 07 Mar 2018 16:28:59 GMT
2 < X-Frame-Options: SAMEORIGIN
2 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
2 < X-Render-Time: 0.0836160182953
2 < ETag: "9ba4d8b2843ee55d6c937244926b40e3"
2 < X-Served-By: app-141
2 < Vary: Accept-Encoding
2 < Vary: Authorization
2 < Content-Length: 5184
2 < X-OAuth-Scopes: pullrequest:write, account
2 < X-Request-Count: 589
2 < Content-Type: application/json; charset=utf-8
2 < 

{"pagelen": 50, "values": [{"description": "* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Testes unitarios\r\n\r\n* Teste unitario", "links": {"decline": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/decline"}, "commits": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/commits"}, "self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "comments": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments"}, "merge": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/merge"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}, "activity": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/activity"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/diff"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/approve"}, "statuses": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/statuses"}}, "title": "Feature/PRJ-371", "close_source_branch": false, "merge_commit": null, "destination": {"commit": {"hash": "2c9177b0f7d8", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2c9177b0f7d8"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject"}, "html": {"href": "https://bitbucket.org/mycompany/myproject"}, "avatar": {"href": "https://bitbucket.org/mycompany/myproject/avatar/32/"}}, "type": "repository", "name": "PRJinity - BackEnd - Project", "full_name": "mycompany/myproject", "uuid": "{66154193-94fc-4f01-88ea-ad7bcc66f955}"}, "branch": {"name": "develop"}}, "state": "OPEN", "closed_by": null, "summary": {"raw": "* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Comment\r\n\r\n* Testes unitarios\r\n\r\n* Teste unitario", "markup": "markdown", "html": "<ul>\n<li>\n<p>Comment</p>\n</li>\n</ul>", "type": "rendered"}, "source": {"commit": {"hash": "2891c04a0c37", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2891c04a0c37"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject"}, "html": {"href": "https://bitbucket.org/mycompany/myproject"}, "avatar": {"href": "https://bitbucket.org/mycompany/myproject/avatar/32/"}}, "type": "repository", "name": "PRJinity - BackEnd - My project", "full_name": "mycompany/myproject", "uuid": "{66154193-94fc-4f01-88ea-ad7bcc66f955}"}, "branch": {"name": "feature/PRJ-371"}}, "comment_count": 4, "author": {"username": "myuser01", "display_name": "myuser Moraes", "type": "user", "uuid": "{f260a384-e79c-4fcb-8712-ec3b8c75f553}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/myuser01"}, "html": {"href": "https://bitbucket.org/myuser01/"}, "avatar": {"href": "https://bitbucket.org/account/myuser01/avatar/32/"}}}, "created_on": "2018-03-05T14:22:02.951008+00:00", "reason": "", "updated_on": "2018-03-07T16:27:11.686550+00:00", "type": "pullrequest", "id": 14, "task_count": 0}], "page": 1, "size": 1}
[INFO] 16:28:59.438 [sonar4bitbucket] Plug-in is active and will analyze pull request with #14...
Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 3 * Client out-bound request
3 > POST https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2891c04a0c37/statuses/build
3 > Content-Type: application/json
3 > Accept: application/json
3 > Authorization: Bearer MYTOKEN
{"name":"Sonar analysis","state":"INPROGRESS","url":"https://sonar.mycompany.com/dashboard?id=br.com.mycompany:myproject:feature%2FPRJ-371","description":"Sonar analysis in progress...","key":"SONAR-ANALYSIS-PR-14"}

Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 3 * Client in-bound response
3 < 201
3 < X-Accepted-OAuth-Scopes: repository
3 < X-Credential-Type: oauth2
3 < Server: nginx
3 < X-Content-Type-Options: nosniff
3 < Connection: keep-alive
3 < X-Static-Version: 8f1aaf1af99e
3 < X-Version: 8f1aaf1af99e
3 < Date: Wed, 07 Mar 2018 16:28:59 GMT
3 < X-Frame-Options: SAMEORIGIN
3 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
3 < X-Render-Time: 0.109143018723
3 < ETag: "ce681e149e3417f70241b271d647f47d"
3 < X-Served-By: app-142
3 < Vary: Accept-Encoding
3 < Vary: Authorization
3 < Content-Length: 1697
3 < X-OAuth-Scopes: pullrequest:write, account
3 < X-Request-Count: 463
3 < Location: /2.0/repositories/mycompany/myproject/commit/2891c04a0c3729428521667ec072f0f534374432/statuses/build/SONAR-ANALYSIS-PR-14
3 < Content-Type: application/json
3 < 
{"key": "SONAR-ANALYSIS-PR-14", "description": "Sonar analysis in progress...", "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject"}, "html": {"href": "https://bitbucket.org/mycompany/myproject"}, "avatar": {"href": "https://bitbucket.org/mycompany/myproject/avatar/32/"}}, "type": "repository", "name": "PRJinity - BackEnd - My project", "full_name": "mycompany/myproject", "uuid": "{66154193-94fc-4f01-88ea-ad7bcc66f955}"}, "url": "https://sonar.mycompany.com/dashboard?id=br.com.mycompany:myproject:feature%2FPRJ-371", "links": {"commit": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2891c04a0c3729428521667ec072f0f534374432"}, "self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2891c04a0c3729428521667ec072f0f534374432/statuses/build/SONAR-ANALYSIS-PR-14"}}, "refname": null, "state": "INPROGRESS", "created_on": "2018-03-07T16:28:59.513228+00:00", "commit": {"hash": "2891c04a0c3729428521667ec072f0f534374432", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/commit/2891c04a0c3729428521667ec072f0f534374432"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/commits/2891c04a0c3729428521667ec072f0f534374432"}}}, "updated_on": "2018-03-07T16:28:59.513250+00:00", "type": "build", "name": "Sonar analysis"}

Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 4 * Client out-bound request
4 > GET https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments?page=1&pagelen=50&=
4 > Accept: application/json
4 > Content-Type: application/json
4 > Authorization: Bearer MYTOKEN

Mar 07, 2018 4:28:59 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 4 * Client in-bound response
4 < 200
4 < X-Accepted-OAuth-Scopes: pullrequest
4 < X-Credential-Type: oauth2
4 < Server: nginx
4 < X-Content-Type-Options: nosniff
4 < Connection: keep-alive
4 < X-Static-Version: 8f1aaf1af99e
4 < X-Version: 8f1aaf1af99e
4 < Date: Wed, 07 Mar 2018 16:28:59 GMT
4 < X-Frame-Options: SAMEORIGIN
4 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
4 < X-Render-Time: 0.121684074402
4 < ETag: "413906517ee64aabbf3d4ae26f0653f8"
4 < X-Served-By: app-140
4 < Vary: Accept-Encoding
4 < Vary: Authorization
4 < Content-Length: 9725
4 < X-OAuth-Scopes: pullrequest:write, account
4 < X-Request-Count: 430
4 < Content-Type: application/json; charset=utf-8
4 < 
{"pagelen": 50, "values": [{"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments/57927224"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14/_/diff#comment-57927224"}}, "deleted": true, "pullrequest": {"type": "pullrequest", "id": 14, "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}}, "title": "Feature/PRJ-371"}, "content": {"raw": "", "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2018-03-05T14:49:24.382787+00:00", "user": null, "updated_on": "2018-03-06T20:00:07.855590+00:00", "type": "pullrequest_comment", "id": 57927224}, {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments/58054169"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/diff/mycompany/myproject:1ea4347bd5a4..2c9177b0f7d8?path=src%2Fmain%2Fjava%2Fbr%2Fcom%2Fmycompany%2FPRJinity%My project%2Frepository%2FItemEmissaoRepository.java"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14/_/diff#comment-58054169"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 14, "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}}, "title": "Feature/PRJ-371"}, "content": {"raw": "Alterar a forma como os status est䯠na query para n䯠utilizar magic numbers. [https://rules.sonarsource.com/java/type/Code Smell/RSPEC-109](https://rules.sonarsource.com/java/type/Code%20Smell/RSPEC-109)\n\nComment. <a href=\"https://rules.sonarsource.com/java/type/Code%20Smell/RSPEC-109\" rel=\"nofollow\">https://rules.sonarsource.com/java/type/Code Smell/RSPEC-109</a></p>\n<pComment.</p>", "type": "rendered"}, "created_on": "2018-03-06T14:05:16.979945+00:00", "user": {"username": "myuser", "display_name": "myuser Almeida", "type": "user", "uuid": "{d5f24a25-32b1-44a0-ad29-dbfa34b271fd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/myuser"}, "html": {"href": "https://bitbucket.org/myuser/"}, "avatar": {"href": "https://bitbucket.org/account/myuser/avatar/32/"}}}, "inline": {"to": 45, "from": null, "path": "src/main/java/br/com/mycompany/PRJinity/My project/repository/ItemEmissaoRepository.java"}, "updated_on": "2018-03-06T14:05:16.984652+00:00", "type": "pullrequest_comment", "id": 58054169}, {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments/58054339"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/diff/mycompany/myproject:65a155efedf7..2c9177b0f7d8?path=src%2Fmain%2Fjava%2Fbr%2Fcom%2Fmycompany%2FPRJinity%My project%2Fcontroller%2FItemEmissaoController.java"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14/_/diff#comment-58054339"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 14, "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}}, "title": "Feature/PRJ-371"}, "content": {"raw": "Existe algum motivo para receber `List<Long> `sendo que sempre 顡tualizado apenas um item?", "markup": "markdown", "html": "<p>Existe algum motivo para receber <code>List&lt;Long&gt;</code>sendo que sempre 顡tualizado apenas um item?</p>", "type": "rendered"}, "created_on": "2018-03-06T14:06:23.752011+00:00", "user": {"username": "myuser", "display_name": "myuser Almeida", "type": "user", "uuid": "{d5f24a25-32b1-44a0-ad29-dbfa34b271fd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/myuser"}, "html": {"href": "https://bitbucket.org/myuser/"}, "avatar": {"href": "https://bitbucket.org/account/myuser/avatar/32/"}}}, "inline": {"to": 81, "from": null, "path": "src/main/java/br/com/mycompany/PRJinity/My project/controller/ItemEmissaoController.java"}, "updated_on": "2018-03-06T14:06:23.756039+00:00", "type": "pullrequest_comment", "id": 58054339}, {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments/58097398"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14/_/diff#comment-58097398"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 14, "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}}, "title": "Feature/PRJ-371"}, "content": {"raw": "**SonarQube Analysis** reported no issues. Take a chocolate :-)\n\nNote that only issues with severity >= ![MINOR](https://raw.githubusercontent.com/mibexsoftware/sonar-bitbucket-plugin/master/src/main/resources/images/severity/MINOR.png) (minor) are reported.", "markup": "markdown", "html": "<p><strong>SonarQube Analysis</strong> reported no issues. Take a chocolate :-)</p>\n<p>Note that only issues with severity &gt;= <img alt=\"MINOR\" src=\"https://raw.githubusercontent.com/mibexsoftware/sonar-bitbucket-plugin/master/src/main/resources/images/severity/MINOR.png\" /> (minor) are reported.</p>", "type": "rendered"}, "created_on": "2018-03-06T20:00:08.029415+00:00", "user": {"username": "mycompany", "display_name": "Seguros Sura", "type": "team", "uuid": "{99f2c59d-5781-445a-b13e-1b250c32361d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/teams/mycompany"}, "html": {"href": "https://bitbucket.org/mycompany/"}, "avatar": {"href": "https://bitbucket.org/account/mycompany/avatar/32/"}}}, "updated_on": "2018-03-06T20:00:08.033891+00:00", "type": "pullrequest_comment", "id": 58097398}, {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14/comments/58181179"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/diff/mycompany/myproject:947f6fd2b81c..2c9177b0f7d8?path=src%2Fmain%2Fjava%2Fbr%2Fcom%2Fmycompany%2FPRJinity%My project%2Fbusiness%2FItemEmissaoServiceImpl.java"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14/_/diff#comment-58181179"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 14, "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/mycompany/myproject/pullrequests/14"}, "html": {"href": "https://bitbucket.org/mycompany/myproject/pull-requests/14"}}, "title": "Feature/PRJ-371"}, "content": {"raw": "comment`n䯠顣laro. comment(https://bitbucket.org/repo/4pMgjyx/images/1361746028-image.png 'image.png')", "markup": "markdown", "html": "<p>Comment:</p>\n<p><img alt=\"image.png\" src=\"https://bitbucket.org/repo/4pMgjyx/images/1361746028-image.png\" title=\"image.png\" /></p>", "type": "rendered"}, "created_on": "2018-03-07T14:01:08.204632+00:00", "user": {"username": "myuser", "display_name": "myuser Almeida", "type": "user", "uuid": "{d5f24a25-32b1-44a0-ad29-dbfa34b271fd}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/myuser"}, "html": {"href": "https://bitbucket.org/myuser/"}, "avatar": {"href": "https://bitbucket.org/account/myuser/avatar/32/"}}}, "inline": {"to": 81, "from": null, "path": "src/main/java/br/com/mycompany/PRJinity/myproject/business/ItemEmissaoServiceImpl.java"}, "updated_on": "2018-03-07T14:01:08.209241+00:00", "type": "pullrequest_comment", "id": 58181179}], "page": 1, "size": 5}

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.166 s
[INFO] Finished at: 2018-03-07T16:28:59+00:00
[INFO] Final Memory: 41M/851M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project myproject: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project myproject: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:108)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:145)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:149)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:312)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:148)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:172)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:319)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:41)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:25)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:25)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:54)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:81)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:77)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy23.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:63)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>`

### Plug-in version, SonarQube version, CI system, build type
Stack:
Sonar for Bitbucket Cloud,
CI system: Bitbucket Pipeline, 
SonarQube version: v6.4

**Comment by MaDDoGo** [comment]
Hi, 

I am facing the same problem but I see this https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/67

Maybe this is solving the issue ;)
